name: Build

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Installing ninja
      run: |
        sudo apt install ninja-build
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
    - name: Build
      run: |
        cmake -B build -GNinja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=26 -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-26 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -Dvenus && ninja -C build
    - name: Store virgl_test_server
      uses: actions/upload-artifact@v3
      with:
        name: virgl_test_server
        path: ./build/virgl_test_server
    
